# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-30 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('name', models.CharField(max_length=64, verbose_name='评论名称')),
                ('title', models.CharField(max_length=64, verbose_name='评论标题')),
                ('content', models.CharField(max_length=360, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('arts', models.ForeignKey(db_column='arts_com_id', on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Arts', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
                'db_table': 'comment',
            },
        ),
    ]
