# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-30 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='arts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Arts', verbose_name='书籍'),
        ),
    ]
