# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, verbose_name='书籍ID')),
                ('title', models.CharField(max_length=64, verbose_name='书籍标题')),
                ('des', models.CharField(max_length=1000, verbose_name='描述')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('page_img', models.ImageField(upload_to='title_img/%Y%m%d', verbose_name='封面')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(1, '未删除'), (2, '已删除')], verbose_name='控制字段')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
                'db_table': 'arts',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='章节ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('cha_content', models.CharField(max_length=1000, verbose_name='章节内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=1, verbose_name='创建时间')),
                ('arts', models.ForeignKey(db_column='arts_id', on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Arts', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '章节信息',
                'verbose_name_plural': '章节信息',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('tag', models.CharField(max_length=64, verbose_name='标签')),
                ('tag_des', models.CharField(max_length=1000, verbose_name='标签描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=1, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(1, '未删除'), (2, '已删除')], verbose_name='控制字段')),
            ],
            options={
                'verbose_name': '书籍标签',
                'verbose_name_plural': '书籍标签',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('icon', models.ImageField(upload_to='media/%Y%m%d', verbose_name='头像')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('member', models.IntegerField(choices=[(1, '普通会员'), (2, 'VIP会员'), (3, '黄金会员')], default=1, verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='arts',
            name='tags',
            field=models.ForeignKey(db_column='tags_id', on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Tags', verbose_name='书籍标签'),
        ),
    ]
