# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-01 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='des',
            field=models.CharField(max_length=1000, verbose_name='作者'),
        ),
    ]
