# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_apps', '0003_auto_20180801_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='flag',
            field=models.IntegerField(choices=[(0, '待下单'), (1, '已下单')], default=0, verbose_name='购买状态'),
        ),
    ]
