# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('art_apps', '0005_auto_20180806_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True, max_length=0, verbose_name='创建日期')),
                ('oid', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_code', models.CharField(max_length=255, verbose_name='订单号')),
                ('address', models.CharField(max_length=255, verbose_name='配送地址')),
                ('post', models.CharField(max_length=255, verbose_name='邮编')),
                ('receiver', models.CharField(max_length=255, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('user_message', models.CharField(max_length=255, verbose_name='附加信息')),
                ('pay_date', models.DateTimeField(blank=True, max_length=0, null=True, verbose_name='支付时间')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='交易日期')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='确认日期')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '异常'), (-1, '删除')], default=1, verbose_name='订单状态')),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Users', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='商品数量')),
                ('status', models.IntegerField(choices=[(1, '未删除'), (2, '已删除'), (0, '禁止')], default=1, verbose_name='购物状态')),
                ('order', models.ForeignKey(db_column='oid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='art_apps.Orders', verbose_name='订单ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Arts', verbose_name='书籍ID')),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='art_apps.Users', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'shop_car',
            },
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
